name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Lint project
        working-directory: ./client
        run: npm run lint

      - name: Run tests
        env:
          CI: true  # Ensure Jest knows it's running in CI
        working-directory: ./client
        run: npm test

      - name: Build the project
        working-directory: ./client
        run: npm run build
        # Optional: Only if you need to create a production build

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage  # Ensure this path is correct based on where your coverage report is generated
